### PR TITLE
Port bwdist code to ImageMorphology package

### PR DESCRIPTION
**Pull request by tlnagy**
See https://github.com/JuliaImages/Images.jl/issues/883 for more details. This is a simple copy-paste job moving the source and tests over to this package.

### CODE REVIEW

**Comment by tlnagy** [comment]
Hey @johnnychen94 and @timholy could you review this when you get a chance?

**Comment by johnnychen94** [comment]
Thanks for doing this, could you add the original authors to this commit using `--author` feature of git?

https://github.com/JuliaImages/Images.jl/commit/8aa3f8cc14db4061a608813e4fd1849e86508bfb#diff-28113949109eaa2e938fd835df54b814

**Comment by tlnagy** [comment]
@johnnychen94 and @timholy, I updated the PR preserving the original commit history. In case y'all are interesting I used the [following commands](https://stackoverflow.com/questions/1365541/how-to-move-files-from-one-git-repo-to-another-not-a-clone-preserving-history) and it worked quite well!

```
cd repository
git log --pretty=email --patch-with-stat --reverse --full-index --binary -- path/to/file_or_folder > patch
cd ../another_repository
git am --committer-date-is-author-date < ../repository/patch 
```

I think this is ready to go!

**Comment by timholy** [comment]
Thanks for the care and the link! I'll have to use that myself next time I move code.

**Pull request merged**
