### PR TITLE
Add simple examples for dilation and erosion

### PR DESCRIPTION
**Pull request by matsueushi**

### CODE REVIEW

**Comment by matsueushi** [comment]
Sorry, I'm not sure why CI by GitHub Action are cancelled.

**Comment by johnnychen94** [comment]
Thanks for doing this! I'll see what I can do to make the CI pass later today.

**Comment by matsueushi** [comment]
Thanks. Now CI is fine expect for appveyor. The issue seems to be related to the recent change https://github.com/JuliaLang/julia/pull/36107.

**Comment by johnnychen94** [comment]
Thanks for doing this!

**Pull request merged**
